name: mkv-dev
favicon: null
layout_spectrum: 0.3997056810185313
typography_spectrum: 0.9435274901334196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1843639025464654
  lightness: 0.012876819353550673
  saturation: 0.09991670423187315
  rhythmicContrast: 0.7421857605222613
purpose: []
